lib/binary_parser.js
lib/context.js
test/composite_parser.js

Closes #42 
Rebased PR #43 by @shamansir to latest master and added a test.

Allow Parent parser attributes in choice

---

README.md
example/bmp.js
example/classfile.js
example/ip.js
example/jpg.js
example/tcp.js
lib/binary_parser.js
lib/context.js
package-lock.json
package.json
test/composite_parser.js
test/primitive_parser.js

Follow prettier coding style

---

lib/binary_parser.js

Compile parser code in sandbox environment

---

README.md
example/tar.js
lib/binary_parser.js
test/composite_parser.js

Flattened data structure for "nest" types

---

.circleci/config.yml

Publish from CircleCI

---

lib/binary_parser.ts

Inject Buffer into the vm context

---

.circleci/config.yml

Remove dependency to mocha-junit-reporter from published package

---

README.md
lib/binary_parser.ts
test/composite_parser.js
test/primitive_parser.js

Implement readUntil option for buffer

---

.npmignore
package.json

Exclude TypeScript files from package until typings are complete

---

lib/binary_parser.ts
test/composite_parser.js

Follows the camel casing of other methods

change saveoffset -> saveOffset

---

lib/binary_parser.ts

Fix parsing result created in different context

---

README.md
lib/binary_parser.ts
test/composite_parser.js
test/primitive_parser.js

This removes the dependency on Node.js and adds support for `Uint8Array`.

Make fully browser-compatible

---

lib/binary_parser.ts
package.json
test/composite_parser.js
test/primitive_parser.js

Fix "TextDecoder is not defined" issue

---

lib/binary_parser.ts
lib/context.ts

Allow external variables in functions

---

lib/context.ts

Fix external variables in some functions

---

package.json

Fix: Publish typings (.d.ts) files to NPM registry

---

lib/binary_parser.ts

This PR address the problem pointed out in #167

Added parsing context to `.readUntil()` and `.formatter()`

---

lib/binary_parser.ts

Fix wrong types

---

.github/workflows/nodejs.yml
lib/binary_parser.ts
package-lock.json
package.json
test/composite_parser.js
test/primitive_parser.js

feat: remove IE11 & node.js 10 support

---

lib/binary_parser.ts
tsconfig.json

Enable strict type checking

---

lib/binary_parser.ts
test/composite_parser.ts

It was generating invalid code.

Fix assert as method definition

---

README.md
example/bmp.ts
example/classfile.ts
example/elf32.ts
example/ip.ts
example/jpg.ts
example/tcp.ts
lib/binary_parser.ts
test/primitive_parser.ts

Fix typo (endianess -> endianness)

---

lib/binary_parser.ts
test/primitive_parser.ts

Fixes #95
Fixes #35
Fixes #29
Fixes #56
Fixes #71
Fixes #160

Allow long bit field sequences
