- README.md
- lib/binary_parser.js
I changed the string parser default behaviour (it will now assume null terminated string) and added an option for  fixed length string to be stripped of null characters (null-padded string).
> Added string parser the capabilities to strip null in order to correctly read null padded string

- README.md
- lib/binary_parser.js
- test/composite_parser.js
I was using your excellent module to make a parser for DNS packets and ran into a few issues that led me to implement a few new features that I thought you might want to integrate.
I added a formatter option to `array` and `nest` type, used like so:
```
var ARecord = new Parser()
.array('ipv4', {
type: 'uint8',
length: 4,
formatter: function(arr) { return arr.join('.'); }
});
```
And for `readUntil` in array type I made it possible to use a function, like so:
```
// Fully qualified domain name, as per http://tools.ietf.org/html/rfc1035 @ 4.1.4
var fqdnPart = new Parser()
.uint8('len')
.string('label', {
length: function() { return (this.len >> 6 === 3 ? 1 : this.len); }
});
var fqdn = new Parser()
.array('fqdnParts', {
type: fqdnPart,
readUntil: function(lastItem, buf) {
// Read parts …
```
> Added formatter to array & nest and a readUntil function

- lib/binary_parser.js
- test/composite_parser.js
the buffer parser with 'eof' as readUntil option didn't work correctly, the slice of the buffer returned was to short, now it works
> Fix for issue #45, the buffer parser eof option now works

- lib/binary_parser.js
Previously, the sizeOf() function would return NaN if the parser contained a nested parser. The 'Nest' type was an unhandled case in this function; to handle it all you need to do is call the nested parser's own sizeOf() function. I don't think you even really need to check that this.options.type is of a Parser object, since that is ensured in nest()
> Added support for nested parsers in sizeOf function

- README.md
- lib/binary_parser.js
- lib/context.js
- test/composite_parser.js
Introduces a method `.namely(alias)`, which allows user to refer to any parser by name in `.array`, `.choice` and `.nest` methods.
Using this approach, user may reference the parser itself and so be able to parse recursive trees of data:
``` javascript
var stop = Parser.start();
var parser =
Parser.start().namely('self')
.uint8('type')
.choice('data', {
'tag': 'type',
'choices': {
0: stop,
1: 'self',
2: Parser.start().nest('left',  { type: 'self' })
.nest('right', { type: 'self' }),
3: Parser.start().nest('one',   { type: 'self' })
.nest('two',   { type: 'self' })
.nest('three', { type: 'self' })
}
});
//        2
//       / \
//      3   1
//    / | \  \
//   1  0  2  0
//  /     / \
// 0     1   0
//      /
//     0
var buffer = new Buffer([ 
2,
/* left -> */ 3,
/* one   -> */ 1, /* -> …
```
> Recursion, method `namely`

- LICENSE.md
- README.md
Because GitHub recommends:
https://help.github.com/articles/licensing-a-repository/
> Move license text to a separate file

- README.md
- lib/binary_parser.js
- test/composite_parser.js
This pull request adds a new `lengthInBytes` option to `array()`. This is useful when a binary format expresses the size of an array in bytes instead of units of `sizeof(type)`.
> Add lengthInBytes option to array()

- README.md
- lib/binary_parser.js
- test/primitive_parser.js
Add 'greedy' option to strings: parses until a null character or end of the stream is found.
We've found this useful at Swift for parsing our binary format. A similar feature is supported in the Python Construct library that does the same thing: https://github.com/construct/construct/pull/59
> Add 'greedy' option to strings

- lib/binary_parser.js
- test/composite_parser.js
Hi,
A wanted to submit a PR to allow to flatten data structure generated by `choice` type parser items, but when looking at the code I figured out that the current code already allow such a feature when you provide *null* or *empty* string as the `name` parameter of the `choice` method.
e.g.: the following Parser:
```
var parser = Parser.start()
.uint8("tag")
.choice(null, {    // <- Note the null name here
tag: "tag",
choices: {
1: Parser.start()
.uint8("length")
.string("message", { length: "length" }),
3: Parser.start().int32le("number")
}
});
```
would produce parsed object like:
```
{
tag: 1,
length: 12,
message: "hello, world"
}
```
or 
```
{
tag: 3,
number: 12345678
}
```
(Note the flat structure of the objects even with the use of a `choice`)
So this pull request only allow to let …
> Flattened data stucture for "choice" types

- example/jpg.js
Was "assert" called "validate" in an older version? Can't find any use or definition of "validate" in the current one.
> JPG example should use assert, not validate

- example/bmp.js
- example/classfile.js
- example/ip.js
- example/jpg.js
- example/mbr.js
- example/tar.js
- example/tcp.js
```
internal/modules/cjs/loader.js:626
throw err;
^
Error: Cannot find module '../lib/binary_parser'
Require stack:
- /Users/keichi/Projects/private/binary-parser/example/tcp.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
at Function.Module._load (internal/modules/cjs/loader.js:527:27)
at Module.require (internal/modules/cjs/loader.js:681:19)
at require (internal/modules/cjs/helpers.js:16:16)
at Object.<anonymous> (/Users/keichi/Projects/private/binary-parser/example/tcp.js:1:14)
at Module._compile (internal/modules/cjs/loader.js:774:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
at Module.load (internal/modules/cjs/loader.js:641:32)
at Function.Module._load (internal/modules/cjs/loader.js:556:12)
at Function.Module.runMain …
```
> Fix module not found error when running the examples

- lib/binary_parser.ts
- lib/context.ts
- package-lock.json
- package.json
- tsconfig.json
`Parser.generate()` was making calls to the corresponding code generators (`generateXX()`) by their name:
```javascript
this['generate' + this.type](ctx);
```
This PR replaces this with a simple switch-case.
> Remove dynamic calls to generateXX()

- README.md
- lib/binary_parser.ts
- test/primitive_parser.js
Adds {u,}int64 support which was introduced in nodejs 12
https://nodejs.org/api/buffer.html#buffer_buf_readbigint64be_offset
The one conditional on this is that it only supports nodejs v12, and it'll throw a runtime error if you try call it outside of nodejs v12
Closes #26
> add big int 64 support

- README.md
- lib/binary_parser.ts
- test/composite_parser.js
Based off this MR for the most part: https://github.com/keichi/binary-parser/pull/89
This allows for saving the current internal offset to a variable returned to the user.
My use case for this is checking that the offset at the end of a dynamic read matches the length of the input buffer.
Taking suggestions on the name of this, im not sold on `saveoffset`
> add saveoffset method

- README.md
- example/elf32.js
- example/jpg.js
- example/mbr.js
- example/tar.js
- lib/binary_parser.ts
- test/composite_parser.js
- test/primitive_parser.js
> Rename skip() to seek()

- lib/binary_parser.ts
Current generated code has:
```
return vars;
return vars;
```
> Remove redundant return in generated code

- lib/binary_parser.ts
If length was a function, it was being called with every iteration.
> Improve array performance

- lib/binary_parser.ts
- package-lock.json
- package.json
- test/composite_parser.js
- test/primitive_parser.js
Binary Parser not work in old browsers because it's don't have TextDecoder.
fast-text-encoding package added to increase compatibility.
> fix(TextEncoding): Binary Parser not work in old browsers

- package-lock.json
- package.json
Node 8 reached EoL in 2019. We also do not run CI tests using Node 8. Let's clarify that we support Node 10 or higher.
> Drop node 8 support

- README.md
- lib/binary_parser.ts
- test/composite_parser.js
Hi, I've made a local fork of this repo because I needed some features that are not currently available.
This PR adds a `$parent` and a `$root` variable while parsing each structure to be able to reference fields (or use them on callbacks). Context variables are available on `.array()`, `.choice()`, `.nest()` and `.pointer()` methods. This PR should close #10
You can find more documentation on the [README.md](https://github.com/Rzial/binary-parser/blob/master/README.md)
I've also corrected some methods signatures that are wrong
> Added parsing context variables

- README.md
- lib/binary_parser.ts
- test/composite_parser.js
This PR adds an `$index` variable for array parsing. I've only implemented this for the `length` parsing option. Also, this PR refactors the way context variables are added to a named parser to make it more easy to extend if needed.
> Index parsing context variable

- lib/binary_parser.ts
#166 and #169 introduced some improper code in the context (missing semicolons). This don't cause any bug right now, however, it can cause bugs in the future.
> Added missing semicolons on generated code

- lib/binary_parser.ts
This typo can cause some bugged parsers on certain conditions. For example, an array parsing before a choice parsing
> Removed typo on code generation

- .prettierrc
- README.md
- benchmark/bench.js
- example/bmp.js
- example/classfile.js
- example/elf32.js
- example/ip.js
- example/jpg.js
- example/mbr.js
- example/tar.js
- example/tcp.js
- lib/binary_parser.ts
- lib/context.ts
- package.json
- test/composite_parser.js
- test/primitive_parser.js
This PR disables the context variables introduced recently (#166, #169, and  #170) by default. The introduction of context variables degraded the parsing performance for multiple orders of magnitudes because it adds and deletes properties during parsing. Although context variables are useful, I decided to disable context variables by default since binary-parser's primary goal is high parsing performance.
Users will need to call `.useContextVars()` on the parser object to enable context variables.
Closes #173.
> Disable context variables by default

- package.json
- tsconfig.json
The commonjs & esm builds have different tsc targets ('es5' & 'esnext'). The javascript `class` was introduced in es6 (I believe), so the `Parser`s exported from the cjs & esm builds are different due to transpilation and have different characteristics. Example:
```javascript
import { Parser } from 'binary-parser'; // esm
class MyParser extends Parser { ... } // works because Parser is a javascript class and can be extended
```
```javascript
const { Parser } = require('binary-parser');
class MyParser extends Parser { ... } // Parser isn't a class for cjs output so this doesn't work correctly..
```
~This PR sets the target output to es2018, which is a modern target and [100% compatible with node >= 10]( https://stackoverflow.com/a/57607634/11008641). This way the only difference between …
> chore: set shared tsc target (ES6)

- lib/binary_parser.ts
This fixes .string("var", "string with \n in it")
> Escape assert strings

- test/primitive_parser.ts
In [test/primitive_parser.ts:125](https://github.com/keichi/binary-parser/blob/8eacd3e004d8b16a4b2f265cef0bd409f51074ad/test/primitive_parser.ts#L125)
```
bytes.push(parseInt(s.slice(i, i + 8), 2));
```
There is an error if we open the file in VS Code:
```
Argument of type 'number' is not assignable to parameter of type 'never'.ts(2345)
```
This is because on [line 120](https://github.com/keichi/binary-parser/blob/8eacd3e004d8b16a4b2f265cef0bd409f51074ad/test/primitive_parser.ts#L120):
```
const bytes = [];
```
The type of `bytes` is inferred as `never[]`. This patch solves the problem by explicitly initializing `bytes` to an empty `number` array.
> fix test: specify array type

- README.md
- lib/binary_parser.ts
- test/composite_parser.ts
This is just like `nest`, where if the `name` parameter is omitted, then the parsed object is embedded directly into the current object.
The update for the readme assumes that #213 has been merged.
> Make `name` parameter optional for `wrapped`

- README.md
Update readme to explain that we need to call .useContextVars() at the top level. Expained by @keichi  in #217 .
> docs: explain how to call `.useContextVars()`

- package.json
This PR may help with complaints from build systems like webpack 5 and perhaps improve some source maps
```
WARNING in ../../node_modules/binary-parser/dist/esm/binary_parser.mjs
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/cdiesh/src/jbrowse-components/node_modules/binary-parser/dist/esm/binary_parser.js.map' file: Error: ENOENT: no such file or directory, open '/home/cdiesh/src/jbrowse-components/node_modules/binary-parser/dist/esm/binary_parser.js.map'
```
The entire lib and dist folder are used. The dist folder map files are currently not deployed but are referred to be the js files in dist, and the map files, if deployed, would refer to the lib folder. I've made some similar PRs like …
> Fix source map by uploading entire dist folder with map files and lib folder with source

- benchmark/bench.js
- benchmark/package-lock.json
- benchmark/package.json
This will make the benchmark a lot fairer as DataView is pretty optimized in node.js and also because binary-parser itself uses DataView instead of Buffer. Also i upgraded to binparse@2.
Example Results on my machine (Macbook M1 MacOS 14.1).
Before this change:
```
❯ node bench.js
hand-written x 51,715 ops/sec ±0.35% (100 runs sampled)
binparse x 19,540 ops/sec ±0.58% (96 runs sampled)
binary-parser x 149,758 ops/sec ±0.58% (96 runs sampled)
destruct-js x 843 ops/sec ±0.17% (99 runs sampled)
structron x 7,554 ops/sec ±0.55% (97 runs sampled)
Fastest is binary-parser
```
After this change:
```
❯ node bench.js
hand-written x 153,338 ops/sec ±1.84% (95 runs sampled)
binparse x 136,028 ops/sec ±3.38% (92 runs sampled)
binary-parser x 153,768 ops/sec ±0.70% (91 runs sampled)
destruct-js x 844 …
```
> Use DataView instead of Buffer in hand-written benchmark

- lib/binary_parser.ts
The current version of `binary-parser` has a type-coercion problem where an offset of 0 will incorrectly be rejected by `.pointer`. It's caused by this block which coerces `offset=0` into false.
```ts
if (!options.offset) {
throw new Error("offset is required for pointer.");
}
```
This PR simply replaces that check with one that accepts 0 but rejects both `undefined` and `null` (`undefined == null` = `true`)
> Bugfix: Make `pointer` accept offset=0

- example/classfile.ts
This is a more complete parser, that I tested that parse class files more completely.
> Update classfile.ts for better parser
